name: Build with ContainifyCI workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build-go:
    name: Build Go ${{ matrix.runtime }}
    uses: containifyci/engine-ci/.github/workflows/engine-ci-workflow.yml@v0
    secrets: inherit
    permissions:
      contents: write # for checkout
      id-token: write # for authenticating to Google Cloud Platform
      pull-requests: write # for updating pr
    with:
      dockerhub_user: "containifyci"
      install_binary: true
